### ISSUE TITLE
Licencia de recursos y assets

### ISSUE THREAD

**Issue by angrykoala** [JJ/SerU#4]
Aparte de la licencia del código, es necesaria una licencia para recursos, documentación etc... 

Podría ser una creative commons, por ejemplo
* CC0
* CC-by-sa

**Comment by JJ** [comment]
Personalmente prefiero CC-by-sa

**Comment by josealberto4444** [comment]
Sí, yo también preferiría una copyleft.

**Comment by angrykoala** [comment]
Closed due to inactivity
