### ISSUE TITLE
¿Decidimos sobre un logo?

### ISSUE THREAD

**Issue by JJ** [JJ/SerU#5]
¿Algo con un birrete, una toga y una litrona? Los símbolos universitarios de toda la vida...

**Comment by JJ** [comment]
El logo debe incluir un Koala.

**Comment by josealberto4444** [comment]
@JJ Yo pediría que fuera algo así simplón tipo diseño plano (parecido al material design).

**Comment by JJ** [comment]
Por mi vale. ¿Alguien se anima a proponer algo?

**Comment by ghost** [comment]
Dado que la aplicación se centra en datos relativos a la universidad, una propuesta de logo pueden unas flechas (representando la transmisión de datos) sobre un fondo formado por un libro y alguna especie de "casa" muy minimalista (academia).

Para hacerlo minimalista, se pueden tener formas planas grises claras sobre fondo blanco. 

Quizás los datos se pueden representar por unos y ceros, en vez de flechas, para enfatizar los datos más que su transmisión.

¿Qué os parece la idea?

**Comment by josealberto4444** [comment]
@gDanix A mí me parece bien esa idea, pero propongo otra más: un birrete con un cable de enchufe colgando. A ver si para el lunes hago un dibujo y lo mando.

**Comment by JJ** [comment]
¡Genial!

**Comment by josealberto4444** [comment]
A esto es a lo que me refería. He hecho el dibujo así rápido y muy mal (grosores, proporciones, alineación...), pero para dar una idea de lo que tenía en mente está bien. De todas formas, no me convence mucho que el birrete tenga más protagonismo que el enchufe (aunque quizá deba ser así, puesto que lo importante es que es para la universidad, no que es una aplicación, ¿no?). ¿Qué opináis?

[birrete.pdf](https://github.com/JJ/SerU/files/1172540/birrete.pdf)

**Comment by JJ** [comment]
Como principio está bien. Quizás más grande el cable y el enchuve. ¿Puedes subir la fuente?
