### ISSUE TITLE
Ingeniería de horarios.

### ISSUE THREAD

**Issue by spothound** [JJ/SerU#8]
¿Cómo veis hacer algún que otro scraper p'a extraer los horarios de las distintas asignaturas y ajín poder programar algún cacharro que haga ingeniería de horarios por ti para ver en qué grupos te puedes meter p'a que no se te solapen las asignaturas? 

Saludos musicales :)

**Comment by JJ** [comment]
Lo veo complicado. ¿Hay un formato común para los horarios?

**Comment by nacheteam** [comment]
Yo también lo veo difícil ya que por lo menos en mi caso los horarios se dan con un fichero PDF y el formato dentro de dicho fichero evidentemente varía entre carreras. Que yo sepa no hay ninguna web de la universidad que proporcione los horarios en otro formato más legible por un programa. Casi que esto habría que hacerlo a mano...

**Comment by JJ** [comment]
Ah, si alguien se molestara en hacer esta información visible y legible en el portal de datos abiertos...

**Comment by spothound** [comment]
también es verdad. Claro, para cada carrera habrá un formato y para cada universidad...

**Comment by JJ** [comment]
Pero creo que hay una aplicación de horarios común. Al menos teóricamente,
debería de ser posible tenerlos en un formato uniforme.
